# PyTorch

### Tensor Functions

PyTorch is a libray or framework that interlopes with other mathematical libraries to decrease computaional time. Also functions specified in this notebook 
- torch.floor()
- torch.half()
- torch.mul()
- torch.histc()
- torch.div()

In [9]:
# Import torch and other required modules
import torch

## Function 1 - torch.floor

This function takes a decimals tensor as input and outputs floor values of decimals with one decimal position.

Note that this function doesnt depend on values that come after the decimal place, but only returns the floor of the values in the tensor.

In [29]:
'''Using a two dimensional tensor'''

Example_1a = torch.tensor([[1.222, 0.2],
                          [35.11, .024]])
torch.floor(Example_1a)

tensor([[ 1.,  0.],
        [35.,  0.]])

In [26]:
Example_1b = torch.tensor([[[0.4, 0.55, 5.5],
                            [4.521 ,5.412, 7.129],
                            [7.22, 1.813, 2.901]]])
torch.floor(Example_1b)

tensor([[[0., 0., 5.],
         [4., 5., 7.],
         [7., 1., 2.]]])

3 dimensional Array with 3 rows and 3 columns returned a tensor of floor values. 

In [200]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[1, 2], [3, 4, 5]])

ValueError: expected sequence of length 2 at dim 1 (got 3)

Finding the floor for this tensor, proved impossible because tensor sequence or dimension was a mismatch

Overrall use of this function can be useful in cases where only whole numbers are preferef for computation or in situations where discrete values would be needed instead of continuous values

## Function 2 - Torch.half

half() function or method takes a tensor and returns a desired memory format of the returned Tensor. it has a memory_format hyperparameter thats used to specify the desired format. and it takes; 
- torch.contiguous_format that decreases order of non-overlapping memory strides represented by values 
- torch.channels_last that increases order of non-overlapping memory strides  
- torch.preserve_format that preserves memory_format of the input tensor

In [47]:
#Example 1 - Trial with 1d array
half_1d = torch.tensor(5.)
print(half_1d.dtype)
HalfExamp_1 = half_1d.half(memory_format=torch.contiguous_format)
print(HalfExamp_1.dtype)

torch.float32
torch.float16


In the above example we shpw the usefulness of half on a 1d array with memoryspace of float32 in decreasing memory size to float16.

In [51]:
# Example 2 - Trial with 1d array
half_1d = torch.tensor(5)
print(half_1d , half_1d.dtype)
HalfExamp_1 = half_1d.half(memory_format=torch.contiguous_format)
print(HalfExamp_1)

tensor(5) torch.int64
tensor(5., dtype=torch.float16)


In the above Example we will examine the effects of half on int64 dtype tensor. half() ends up changing the memory_format into a float64 dtype tensor

In [60]:
# Example 3 - breaking (to illustrate when it breaks)
half_1d = torch.tensor(5)
print(half_1d , half_1d.dtype)
HalfExamp_1 = half_1d.half(memory_format =float)
print(HalfExamp_1)

tensor(5) torch.int64


TypeError: half(): argument 'memory_format' must be torch.memory_format, not type

In this we illustrate that specifying a wrong value or dtype value within the memory_format attribute will lead to an error

This half function can really be useful when working with huge tensors with extremely huge memory sizes since we can reduce it to enhance processing speed, time complexity  and memory usage for images or csv's

## Function 3 - Torch.mul

This function takes two arguments , first being the tensor of any ndim and second being the scalar in value.multiplies the tensor to the scaler

In [167]:
#Example 1  3d tensor
torch.mul(integer_1 , 10)

tensor([[[ 15.,   2., 101.],
         [ 40.,  17.,   9.],
         [ 50.,  70., 100.]]])

In the above example, results in a multiplication of the first argument (integer_1) by the second (scaler = 10)

In [194]:
# Example 2 - returns a 1d tensor with
integer_2 = torch.tensor([ _ for _ in integer_1[0][1]  ])
print(integer_2 , integer_2.ndim , integer_2.shape)

torch.mul(integer_2 , torch.tensor([10 , 5 , 2]) )

tensor([4.0000, 1.7000, 0.9000]) 1 torch.Size([3])


tensor([40.0000,  8.5000,  1.8000])

In the above code we create a 1 dimensional tensor with size of 3 from a 3 dimensional tensor and then pass the new tensor(integer_2) as the first argument of torch.mul() with a new tensor as the second argument.  this results in each index value in the first argument multiplying the corresponding index value in the second.

In [180]:
# Example 3 - breaking (to illustrate when it breaks)
'''Code breaks because second argument must either be a tensor or scaler'''
integer_2 = torch.tensor([ _ for _ in integer_1[0][1]  ])
torch.mul(integer_2 , [10 , 5] )

TypeError: mul(): argument 'other' (position 2) must be Tensor, not list

In [185]:
# Example 4 - breaking (to illustrate when it breaks)
integer_2 = torch.tensor([ _ for _ in integer_1[0][1]  ])
torch.mul(integer_2 , torch.tensor([10 , 5]) )

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

Example 3 & 4 both break because operations with mul can only be between tensors and scalers

overrall use of this depends on the task at hand. since comparison with * yield same processing time.

## Function 4 - Torch.histc

torch.histc takes a tensor as input, and returns a histogram as a tensor. The elements are sorted into equal width bins between min and max. If min and max are both zero, the minimum and maximum values of the data are used.

In [117]:
# Example 1 - 2d tensor with float32
integer_1 = torch.tensor([[0.1, .22, .5],
                         [6., .7, .9] ])
print(integer_1.dtype)
Example_1 = torch.histc(integer_1,bins=1 , min=0, max=0)
print(Example_1.dtype)
Example_1

torch.float32
torch.float32


tensor([6.])

Illustrated with 1 bin and with min and max set to zero. Summing up the number of values in the tensor into one bin in the histogram

In [118]:
# Example 2  - 3d tensor with float32
integer_1 = torch.tensor([[[1.5, .2, 10.1],
                           [4., 1.7, .9],
                           [5 , 7 , 10]]])
print(integer_1.dtype)
Example_1 = torch.histc(integer_1, bins=9, min=0, max=10)
print(Example_1.dtype)
Example_1

torch.float32
torch.float32


tensor([2., 2., 0., 1., 1., 0., 1., 0., 1.])

Illustrated with 9 bins and one each for each value in the tensor

In [119]:
# Example 3 - breaking (to illustrate when it breaks)

integer_1 = torch.tensor([[[1.5, .2, 10.1],
                           [4., 1.7, .9],
                           [5 , 7 , 10]]])
print(integer_1.dtype)
Example_3 = torch.histc(integer_1, bins=0, min=0, max=0)
print(Example_1.dtype)
Example_3

torch.float32


RuntimeError: bins must be > 0 at C:\w\b\windows\pytorch\aten\src\TH/generic/THTensorMoreMath.cpp:950

Bins must greater than zero or else tensors cannot be computed in the histogram tensor

This function will likely be useful in image processing when figuring out rows and columns with high pixel intensity

## Function 5 - Torch.div

This function takes two arguments , first being the tensor of any ndim and second being the scalar in value dividing the tensor

In [132]:
integer_1

tensor([[[ 1.5000,  0.2000, 10.1000],
         [ 4.0000,  1.7000,  0.9000],
         [ 5.0000,  7.0000, 10.0000]]])

In [123]:
# Example 1  - with a 3d tensor
print(integer_1.ndim)
Example_1 = torch.div(integer_1 , 5)
Example_1

3


tensor([[[0.3000, 0.0400, 2.0200],
         [0.8000, 0.3400, 0.1800],
         [1.0000, 1.4000, 2.0000]]])

results in a division of the first argument (integer_1) by the second (scaler = 5)

In [150]:
'''
# Example 2 
integer_2 = torch.tensor([ 10*_+ __ for _ in integer_1[0][1] for __ in integer_1[0][0] ])
torch.div(integer_2, 5)
'''
# Example 2 
integer_2 = torch.tensor([ 10*_ for _ in integer_1[0][1]  ])
torch.div(integer_2, 5)

tensor([8.0000, 3.4000, 1.8000])

integer_2 computes a list comprehension of the second row in the tensor, times 10. And in the next line, uses torch.div() to divide integer_2 by 5 

In [151]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 
torch.div([ 10*_ for _ in integer_1[0][1] ] , 5)

TypeError: div(): argument 'input' (position 1) must be Tensor, not list

In the Example above, the code broke due to the fact that torch.div accepts only tensors and because the list comprehension hasnt been converted into a tensor yet

Over use of this function has multiple applications in computations involving data numerical tables, image processing and neural networks

## Conclusion

In this notebook we have looked at 
 - functions that return whole values by flooring tensors.
 - funtions that help in affect memory complexity by modifying non overlapping memory strides.
 - functions that help in returning multipications of tensors and scalers  and tensors and tensors.
 - functions that help in returns a tensor histogram of values in a tensor.
 - functions that help in returning tensors divisions of tensors and scalers and tensors and tensors.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [0]:
#!pip install jovian --upgrade --quiet

In [201]:
import jovian

In [204]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "troublem1/01-tensor-operations-1a3b5" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..


TypeError: invalid cmd type (<class 'NoneType'>, expected string)