In [211]:
#import needed modules

import torch
import numpy as np

In [212]:
#input(temp , rainfall , humidity)
inputs = np.array([ [73,67,43],
                    [91,88,64],
                    [87,134,58],
                    [102,43,37],
                    [69,96,70]],  dtype='float32')

In [213]:
#targets( apples , oranges)

targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]] , dtype='float32')

In [214]:
#convert input and target arrays to tensors
'''
inputs = torch.tensor(inputs)
targets = torch.tensor(targets)
'''


inputs = torch.from_numpy(inputs)

targets = torch.from_numpy(targets)

inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

# Linear Regression model from scratch

In [215]:
#set random weights and constants/bias using torch.rand

beta = torch.rand(2,3 , requires_grad=True)
const = torch.rand(2 , requires_grad=True)
print(beta)
print(const)

tensor([[0.8789, 0.7751, 0.9036],
        [0.7219, 0.1678, 0.1189]], requires_grad=True)
tensor([0.2075, 0.2309], requires_grad=True)


Formular for linear_model : Input_matrix x beta_matrix.T + const_matrix

In [216]:
#define a linear_model

def linear_model(x):
    return x @ beta.t() + const

In [217]:
#Generate Predictions
first_pred = linear_model(inputs)    #far off the actuals since our model was
print(first_pred)                    #initialized with random weights/beta and constant/bias

tensor([[155.1545,  69.2775],
        [206.2273,  88.2900],
        [232.9442,  92.4068],
        [156.6203,  85.4716],
        [198.5127,  74.4646]], grad_fn=<AddBackward0>)


# Loss Function

To improve the model, we evaluate how the model is performing by comparing prediction with actual targets.
- Calculate the difference between the actual predicted.
- Square the difference to remove all negative values
- find the average of the elements in the resultant.

The result is a single number, Mean_squarred_error ('MSE')

In [218]:
# MSE_ LOSS 
def mse_calculator(tensor_1 , tensor_2):
    diff= tensor_1-tensor_2
    return torch.sum(diff* diff)/diff.numel()

In [219]:
loss = mse_calculator(first_pred , targets)
print(loss)            #on average, each element is 61 (np.sqrt(3685)) away from the actual element

tensor(7188.4844, grad_fn=<DivBackward0>)


# Compute Gradients

In [220]:
#compute  gradients
#loss is a function of the weights, as we change the weight the loss changes
loss.backward()

In [221]:
print(beta)
print(beta.grad)

tensor([[0.8789, 0.7751, 0.9036],
        [0.7219, 0.1678, 0.1189]], requires_grad=True)
tensor([[ 9773.7510,  9577.9551,  6110.7593],
        [ -573.9607, -1759.5005,  -904.5890]])


In [222]:
#backward computes grads and keeps adding to the grads.So, we Set gradients back to zero after first computations

beta.grad.zero_()
#const.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Adjust Weights and biases using Gradient Descent

lets improve our model using gradient descent optimazation algorithm using these steps

- Generate predictions
- Calculate the loss
- Set backward on loss and Compute the gradients w.r.t to the weights and bias
- Adjust the weights by subtracting a small quantity proportional to the gradient
- Reset the gradients back to zero

In [223]:
#Generate predictions
first__pred = linear_model(inputs)
print(first_pred)

tensor([[155.1545,  69.2775],
        [206.2273,  88.2900],
        [232.9442,  92.4068],
        [156.6203,  85.4716],
        [198.5127,  74.4646]], grad_fn=<AddBackward0>)


In [224]:
#Calculate loss
loss = mse_calculator(first__pred, targets)
print(loss)

tensor(7188.4844, grad_fn=<DivBackward0>)


In [225]:
print(beta)
print(const)

tensor([[0.8789, 0.7751, 0.9036],
        [0.7219, 0.1678, 0.1189]], requires_grad=True)
tensor([0.2075, 0.2309], requires_grad=True)


In [226]:
# Compute Gradients
loss.backward()
print(beta.grad)
print(const.grad)

tensor([[ 9773.7510,  9577.9551,  6110.7593],
        [ -573.9607, -1759.5005,  -904.5890]])
tensor([227.3836, -20.0358])


- if gradients are positive, we decrease weights to  reduce loss
- if gradients are negative we increase weights to reduce loss

In [227]:
# Adjust weights and reset gradient to zero
with torch.no_grad():
    beta -= beta.grad * 0.00005
    const -= const.grad * 0.00005
    beta.grad.zero_()
    const.grad.zero_()

In [228]:
print(beta.grad)
print(const.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


 ### Train on Multiple epoch

In [229]:
for i in range(200):
    first_preds = linear_model(inputs)
    loss = mse_calculator(first_preds, targets)
    loss.backward()
    with torch.no_grad():
        beta -= beta.grad * 0.00005
        const -= const.grad * 0.00005
        beta.grad.zero_()
        const.grad.zero_()

In [230]:
# Calculate the loss
eval_pred = linear_model(inputs)
loss = mse_calculator(eval_pred , targets)
print(loss)

tensor(4.1982, grad_fn=<DivBackward0>)


In [231]:
#predictions
eval_pred

tensor([[ 57.2266,  70.5896],
        [ 82.0496,  98.7489],
        [118.9526, 136.8778],
        [ 21.2340,  38.2128],
        [101.5952, 115.1413]], grad_fn=<AddBackward0>)

In [232]:
#Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### Commit  Linear_Reg_Notebook

In [204]:
import jovian

In [ ]:
jovian.commit()